### ISSUE TITLE
After restore we see two default-tokens in some namespaces - why do we backup and restore the default token?

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/backup-restore-operator#165]
SURE-3501

Just have done a backup and restore in Rancher 2.5.9 with the backup-operator and had to realize that there are two default-tokens in all namespaces!

```
 kubectl get secret -n fleet-system
NAME                                     TYPE                                  DATA   AGE
default-token-cg6wp                      kubernetes.io/service-account-token   3      81m
default-token-zppdx                      kubernetes.io/service-account-token   3      81m
fleet-agent-token-5rr2b                  kubernetes.io/service-account-token   3      81m

```

Is this a bug or per design?

**Comment by sgapanovich** [comment]
I tried to reproduce the issues with duplicate default-tokens and I couldn't 

rancher versions: 2.5.9 / 2.5.12-rc2 / 2.6-head 
backup operators: 1.2.0 (for 2.5.x) / 2.1.0 (for 2.6.x)
rancher server install: tried both docker and HA

repro steps:
1. create rancher (docker or HA)
2. create downstream clusters 
3. create users
4. create roles
5. create cluster templates
6. install back up
7. take note of the default tokens and count in the local cluster (`kubectl get secret -A | grep default- | wc -l`)
7. take back up
8. create more users, roles, cluster templates
9. restore to the same cluster
10. check that all resources created in step 8 are gone
11. check secrets and their count

didn't see extra token created

@Martin-Weiss  were you able to see the issue more than once? 
are there anything specific steps required besides described above?

**Comment by Martin-Weiss** [comment]
The issue happens in case you restore to a "fresh" cluster.

**Comment by sgapanovich** [comment]
Tried on 2.5.x and 2.6.x and was able to see the issue in both setups

----------

### Repro Environment: ###
Rancher version: 
  -v2.5-8fba445092b0565fc0c333d415f89596d850462b-head 
  -v2.6-e8a87f42b3a697164549a81dcc6b3a9238e5e4c4-head
Rancher cluster type: HA
Docker version: 20.10
Rancher backup version: 1.2.0 (for 2.5.x) and 2.1.0 (for 2.6.x)

----------

### Repro steps: ###
1. create a HA rke1 cluster
2. install Rancher
3. install a backup app
4. take a backup
5. create a fresh HA rke1 cluster
6. migrate your rancher to it 
  https://rancher.com/docs/rancher/v2.5/en/backups/migrating-rancher/
7. check secrets with `kubectl get secret -A | grep default-token`

### Issue: ###
duplicate `default-token-xxxx` created in some namespaces

note: if there is a downstream cluster deployed (in 2.5 or 2.6) `cluster-fleet-default-xxxx` default token created for it as well and then duplicated when migrating rancher

2.5-head
![25](https://user-images.githubusercontent.com/40282141/150041540-b1d092dc-6f84-448b-8b87-7ee4398e0d24.jpg)


2.6-head
![26](https://user-images.githubusercontent.com/40282141/150041548-5c4e7df2-e120-4229-a873-afa3db26b33f.jpg)

**Comment by superseb** [comment]
Root cause for this issue is that namespaces are being restored, which on create trigger a creation of ServiceAccount named `default`, and associated secret of type `service-account-token`. We then restore the service account, but remove the associated secrets which triggers an update (patch) of the ServiceAccount that was created on namespace creation (restore), which means the token-controller will create a new secret for the ServiceAccount as it was patched with removed secrets. That's how we we end up with multiple tokens.

Currently I am testing adding `excludeResourceNameRegexp`, so we can add `excludeResourceNameRegexp: "^default$"` to the `kindsRegexp: "^serviceaccounts$"` resource sets which we traverse for what resources to back-up.

**Comment by Martin-Weiss** [comment]
> In our docs (https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/) we state:
> 
> In the Restore custom resource, prune must be set to false.
> 
> It is unclear why this needs to be false, and leaving it out/setting it to true, seems to resolve this issue as it prunes all resources that are not part of the backup, which would be the auto generated/created secrets.
> 
> The actual root cause seems to be the way that we create/modify service accounts, working on a full write up and solution.
> 
> It would be nice if QA (or maybe @Martin-Weiss) can test if it works as expected with `prune: true` or without `prune` (as it default to `true`), so we know for sure.

Unfortunately I can not test.. and for safety reasons I am not sure if "prune: true" would be valid in a new cluster..

In addition to that I assume we have multiple clusters out there in production, now that have these multiple tokens and need cleanup.. how do we want to do that cleanup?

**Comment by superseb** [comment]
### Root cause
Root cause for this issue is that namespaces are being restored, which on create trigger a creation of ServiceAccount named default, and associated secret of type service-account-token. We then restore the service account, but remove the associated secrets which triggers an update (patch) of the ServiceAccount that was created on namespace creation (restore), which means the token-controller will create a new secret for the ServiceAccount as it was patched with removed secrets. That's how we we end up with multiple tokens.
 
### What was fixed, or what changes have occurred
Exclude serviceaccounts named `default` from being in the backup so they dont get restored.
 
### Areas or cases that should be tested
Normal operation of the cluster after restore

### What areas could experience regressions?
Any pod running on the cluster 

### Are the repro steps accurate/minimal?
Yes, just restore a backup made with the current backup-restore-operator to a newly created cluster.

**Comment by MSpencer87** [comment]
***Verified on v2.1.1-rc4***
Rancher 2.6.4-rc11
rke 1.3.3 -> k8s v1.21.7
![Screen Shot 2022-03-25 at 2 33 09 AM](https://user-images.githubusercontent.com/6477538/160196705-bef2e4de-0789-4b2a-98ab-b8bd6e5613d5.png)
![Screen Shot 2022-03-25 at 2 31 54 AM](https://user-images.githubusercontent.com/6477538/160196709-b4fd6989-93f4-4149-a4ba-b50e203b0199.png)

**Steps for Testing**
1) Deploy HA Rancher
2) Install rancher-backups 2.1.1+up2.1.1-rc4 chart via UI or helm 
3) Create some resources to backup(users, templates etcs)
4) Check secrets -> `kubectl get secrets -A | grep default`
5) Create an s3 backup 
6) Teardown first cluster 
7) Create provider secret and migrationResource files for migration
8) Install rancher-backups 2.1.1+up2.1.1-rc4 chart into second cluster via helm 
9) Apply secret and migrationResource 
10) Check secrets -> `kubectl get secrets -A | grep default`
11) Install rancher onto second cluster
