### ISSUE TITLE
A restore does not move namespaces back to the original project in the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#22]
**On master-head - commit id: `731b33e1a776`, backup restore operator tag: `v0.0.1-rc9`**

- In a HA setup, Deploy a custom cluster --> create a project --> create a namespace --> deploy a workload in this namespace.
- Take a backup b1 (install backup restore operator in the 
- Move the namespace to a different project say `test2`
- restore from b1.
- The namespace is still seen in project `test2`

**Expected:**
Namespace be moved back to the original project

**Comment by mrajashree** [comment]
@sowmyav27 although the namespace denoting a project is created in the management cluster, the actual kubernetes namespaces created in the project live in the downstream user cluster. 
So if you create project `test1` in your custom cluster, and create a namespace `ns1` in it, the namespace denoting `test1` will be in your local cluster, but the namespace `ns1` is in the downstream user cluster. Backup-restore-operator only performs actions on the cluster it is installed on, which is the local cluster. 
As you know the label `field.cattle.io/projectId` on a namespace determines which project it is in. Restore doesn't actually change this label because the namespace `ns1` is in the downstream cluster.
The same use case should work if the projects were in the local cluster. Not sure if this is a common use case, of creating projects in the mgmt cluster, but if it is, then the same set of steps work correctly in the mgmt cluster

**Comment by sowmyav27** [comment]
@mrajashree This will not work on a local cluster unless you give in the particular namespace details in the resourceset to backup. As per offline discussion this will be documented.
