### ISSUE TITLE
Backup not stored to S3: Request Entity Too Large

### ISSUE THREAD

**Issue by jbrinksmeier** [rancher/backup-restore-operator#314]
**Rancher Server Setup**
- Rancher version: v2.5.5
- Installation option (Docker install/Helm Chart): helm
- Kubernetes Version and Engine: v1.17.2

**Describe the bug**
Storing a backup to S3 aborts on upload with `failed to upload backup file: 413 Request Entity Too Large`

**To Reproduce**
1. Install Rancher Backup
2. Create a backup with S3 configuration (here, S3 compatible DigitalOcean Spaces are used) 

**Expected behavior**
Expect: The backup to be uploaded to S3 Bucket

**Additional context**
As a "shot in the dark", the ingress exposing rancher got the annotation `nginx.ingress.kubernetes.io/proxy-body-size: 0` to no avail

**Comment by MKlimuszka** [comment]
Can you see the size of the tar file you are trying to upload? Also, can you check the configuration of your S3 buckets to see what their upload limits are? That looks like the error is coming from your storage provider. A quick search shows that Digital ocean limits uploads to 5GB per part. If you have a backup larger than that, then we'll have to make a feature request in order to split backups into multiple parts.
