### ISSUE TITLE
[CodeQuality] Fix filtering on object's Kind or Name 

### ISSUE THREAD

**Issue by ericpromislow** [rancher/backup-restore-operator#411]
**Describe the bug**
Follow-up to bug BRO #408 : some objects were being stored multiple times, or backed up when they shouldn't have been.

On analysis, the code was not only sometimes incorrect, but the logic was unnecessarily complicated

**Plan**

Most likely we can just cherry-pick the relevant commits from 4.0 to 5.0

**Comment by MKlimuszka** [comment]
https://github.com/mallardduck/backup-restore-operator/pull/1

**Comment by ericpromislow** [comment]
Done as part of resourceset collector PR #415

**Comment by MKlimuszka** [comment]
@ericpromislow , verify which branches these changes have gone into.

**Comment by ericpromislow** [comment]
The changes are in branches `release/v3.0` - commit 0c9956568791501cd186b0b41ca94280c9dd1cfd (last commit)
and `release/v4.0` - commit 18086f5c3cbd577c3d49ecfbcec94c97b13bda50

**Comment by mallardduck** [comment]
As of today these changes should be in all branches uniformly all the way up to 5.0.
Additionally they have been released for:

| Rancher | BRO |
| --- | --- |
| 2.7 | 3.1.3 |
| 2.8 | 4.0.1 |
| 2.9 | 5.0.0-rc3 (TBD) |

I've included 2.9/5.x since as of merge of https://github.com/rancher/backup-restore-operator/pull/432 the changes will be included with the next RC we cut which will be rc3.
