### ISSUE TITLE
Migration error: ServiceAccount "rancher" in namespace "cattle-system" exists and cannot be imported

### ISSUE THREAD

**Issue by travis-sobeck** [rancher/backup-restore-operator#55]
Process: 
- deploy Rancher 2.5/latest to AKS, [configure/schedule backups](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/back-up-rancher/)
- configure Authentication, Cloud Creds, Node Templates, create cluster with node template.
- Delete entire AKS cluster/rancher
- Create new AKS exactly as it was (Terraform) and [recover rancher](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/migrating-rancher/)

Issue: After the cluster is restored it has NO retention of configured Authentication, Cloud Creds, Node Templates, or the cluster that was created (the cluster is fine, but rancher has no idea it even exists.  

Expected behavior: After restoring the cluster I expect it to look like it did when I took the backup, including retention of configured Authentication, Cloud Creds, Node Templates, or the cluster that was created. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.1` UI: `v2.5.0` |
|Route|`undefined`|

**Comment by mrajashree** [comment]
@travis-sobeck okay thanks, the error makes me think this is due to helm version mismatch. Most probably the helm version used for installing rancher on the cluster where backup was taken, is older than the current helm version. Can you share the helm version that was used for installing rancher on the original cluster?
Also moving this issue to the backup-restore-operator repo, we want to use this repository to track related issues
