### ISSUE TITLE
Add Rancher Webhook to the ResourceSet

### ISSUE THREAD

**Issue by nickgerace** [rancher/backup-restore-operator#73]
~~Parent issue: https://github.com/rancher/backup-restore-operator/issues/69~~

This issue no longer has a parent issue due to change in scope.

**Comment by mrajashree** [comment]
Rancher webhook resourceSet will contain validating webhook objects, and when it was a part of the Rancher resourceSet it didn’t get restored correctly due to the current order in which we restore resources. This issue has more details on how we might have to slightly change the restore order for webhooks https://github.com/rancher/backup-restore-operator/issues/45

**Comment by nickgerace** [comment]
Thank you for the context @mrajashree!

**Comment by nickgerace** [comment]
Removal PR for reference: https://github.com/rancher/charts/pull/726

**Comment by nickgerace** [comment]
This is dependent on restore working first: https://github.com/rancher/backup-restore-operator/issues/45

**Comment by cbron** [comment]
Bumping to 2.6

**Comment by jiaqiluo** [comment]
Closing this issue because we do not need to backup the rancher-webhook app, or at least the ValidatingWebhookConfiguration anymore.

See [this comment](https://github.com/rancher/backup-restore-operator/issues/45#issuecomment-834683142) for a detailed explanation.
